CREATE DATABASE EMP;
CREATE TABLE EMP
(NAME VARCHAR(20),
PRODUCT VARCHAR(20),
PRICE INT,
QUANTITY INT);
SELECT * FROM EMP;

INSERT INTO EMP VALUES
('VIKAS','IPHONE',50000,4);
INSERT INTO EMP VALUES
('VINAY','BAG',4500,2),
('HEMLATA','RING',6000,2),
('RAMPRASAD','BIKE',60000,1);

SELECT * FROM EMP WHERE price = (SELECT MAX(price) FROM EMP);
SELECT *FROM EMP WHERE QUANTITY = (SELECT MAX(PRICE) FROM EMP);

CREATE TABLE EMP_SAL
(NAME VARCHAR(20),
PRICE INT,
PRODUCT VARCHAR (20),
QUANTITY INT);
SELECT * FROM EMP_SAL;
INSERT INTO EMP_SAL VALUES
('VIKAS',50000,'IPHONE',5);
INSERT INTO EMP_SAL VALUES
('VINAY',4500,'BAG',2),
('HEMLATA',6000,'RING',2),
('RAMPRASAD',60000,'BIKE',1);

SELECT *FROM EMP
SELECT *FROM EMP_SAL;

ALTER TABLE EMP ADD CONSTRAINT NAME_PK PRIMARY KEY (NAME);

ALTER TABLE EMP ALTER COLUMN NAME VARCHAR(20) NOT NULL;


ALTER TABLE EMP_SAL
ADD CONSTRAINT NAME_FK
FOREIGN KEY (NAME) REFERENCES EMP (NAME);

















